from __future__ import annotations

PIPELINE_SERVICE_LABEL = "data-pipeline"

RAW_EVENT_TABLE = "raw_events"
RAW_MESSAGE_TABLE = "raw_messages"
RAW_LEAD_TABLE = "raw_leads"
ANALYTICS_EVENT_TABLE = "analytics_events"
LEAD_METRICS_TABLE = "lead_metrics"
CONVERSATION_METRICS_TABLE = "conversation_metrics"
SENTIMENT_LOGS_TABLE = "sentiment_logs"

RAW_TABLES = {
    RAW_EVENT_TABLE,
    RAW_MESSAGE_TABLE,
    RAW_LEAD_TABLE,
}

PROCESSED_TABLES = {
    ANALYTICS_EVENT_TABLE,
    LEAD_METRICS_TABLE,
    CONVERSATION_METRICS_TABLE,
    SENTIMENT_LOGS_TABLE,
}

DEFAULT_BATCH_INTERVAL_SECONDS = 3600
DEFAULT_BATCH_INITIAL_DELAY_SECONDS = 15
