const REGION_NAME_OVERRIDES = {
  AC: 'Ascension Island',
  TA: 'Tristan da Cunha',
  XK: 'Kosovo',
};

const RAW_PHONE_COUNTRIES = [
  { code: 'AC', dialCodes: ['+247'] },
  { code: 'AD', dialCodes: ['+376'] },
  { code: 'AE', dialCodes: ['+971'] },
  { code: 'AF', dialCodes: ['+93'] },
  { code: 'AG', dialCodes: ['+1'] },
  { code: 'AI', dialCodes: ['+1'] },
  { code: 'AL', dialCodes: ['+355'] },
  { code: 'AM', dialCodes: ['+374'] },
  { code: 'AO', dialCodes: ['+244'] },
  { code: 'AR', dialCodes: ['+54'] },
  { code: 'AS', dialCodes: ['+1'] },
  { code: 'AT', dialCodes: ['+43'] },
  { code: 'AU', dialCodes: ['+61'] },
  { code: 'AW', dialCodes: ['+297'] },
  { code: 'AX', dialCodes: ['+358'] },
  { code: 'AZ', dialCodes: ['+994'] },
  { code: 'BA', dialCodes: ['+387'] },
  { code: 'BB', dialCodes: ['+1'] },
  { code: 'BD', dialCodes: ['+880'] },
  { code: 'BE', dialCodes: ['+32'] },
  { code: 'BF', dialCodes: ['+226'] },
  { code: 'BG', dialCodes: ['+359'] },
  { code: 'BH', dialCodes: ['+973'] },
  { code: 'BI', dialCodes: ['+257'] },
  { code: 'BJ', dialCodes: ['+229'] },
  { code: 'BL', dialCodes: ['+590'] },
  { code: 'BM', dialCodes: ['+1'] },
  { code: 'BN', dialCodes: ['+673'] },
  { code: 'BO', dialCodes: ['+591'] },
  { code: 'BQ', dialCodes: ['+599'] },
  { code: 'BR', dialCodes: ['+55'] },
  { code: 'BS', dialCodes: ['+1'] },
  { code: 'BT', dialCodes: ['+975'] },
  { code: 'BW', dialCodes: ['+267'] },
  { code: 'BY', dialCodes: ['+375'] },
  { code: 'BZ', dialCodes: ['+501'] },
  { code: 'CA', dialCodes: ['+1'] },
  { code: 'CC', dialCodes: ['+61'] },
  { code: 'CD', dialCodes: ['+243'] },
  { code: 'CF', dialCodes: ['+236'] },
  { code: 'CG', dialCodes: ['+242'] },
  { code: 'CH', dialCodes: ['+41'] },
  { code: 'CI', dialCodes: ['+225'] },
  { code: 'CK', dialCodes: ['+682'] },
  { code: 'CL', dialCodes: ['+56'] },
  { code: 'CM', dialCodes: ['+237'] },
  { code: 'CN', dialCodes: ['+86'] },
  { code: 'CO', dialCodes: ['+57'] },
  { code: 'CR', dialCodes: ['+506'] },
  { code: 'CU', dialCodes: ['+53'] },
  { code: 'CV', dialCodes: ['+238'] },
  { code: 'CW', dialCodes: ['+599'] },
  { code: 'CX', dialCodes: ['+61'] },
  { code: 'CY', dialCodes: ['+357'] },
  { code: 'CZ', dialCodes: ['+420'] },
  { code: 'DE', dialCodes: ['+49'] },
  { code: 'DJ', dialCodes: ['+253'] },
  { code: 'DK', dialCodes: ['+45'] },
  { code: 'DM', dialCodes: ['+1'] },
  { code: 'DO', dialCodes: ['+1'] },
  { code: 'DZ', dialCodes: ['+213'] },
  { code: 'EC', dialCodes: ['+593'] },
  { code: 'EE', dialCodes: ['+372'] },
  { code: 'EG', dialCodes: ['+20'] },
  { code: 'EH', dialCodes: ['+212'] },
  { code: 'ER', dialCodes: ['+291'] },
  { code: 'ES', dialCodes: ['+34'] },
  { code: 'ET', dialCodes: ['+251'] },
  { code: 'FI', dialCodes: ['+358'] },
  { code: 'FJ', dialCodes: ['+679'] },
  { code: 'FK', dialCodes: ['+500'] },
  { code: 'FM', dialCodes: ['+691'] },
  { code: 'FO', dialCodes: ['+298'] },
  { code: 'FR', dialCodes: ['+33'] },
  { code: 'GA', dialCodes: ['+241'] },
  { code: 'GB', dialCodes: ['+44'] },
  { code: 'GD', dialCodes: ['+1'] },
  { code: 'GE', dialCodes: ['+995'] },
  { code: 'GF', dialCodes: ['+594'] },
  { code: 'GG', dialCodes: ['+44'] },
  { code: 'GH', dialCodes: ['+233'] },
  { code: 'GI', dialCodes: ['+350'] },
  { code: 'GL', dialCodes: ['+299'] },
  { code: 'GM', dialCodes: ['+220'] },
  { code: 'GN', dialCodes: ['+224'] },
  { code: 'GP', dialCodes: ['+590'] },
  { code: 'GQ', dialCodes: ['+240'] },
  { code: 'GR', dialCodes: ['+30'] },
  { code: 'GT', dialCodes: ['+502'] },
  { code: 'GU', dialCodes: ['+1'] },
  { code: 'GW', dialCodes: ['+245'] },
  { code: 'GY', dialCodes: ['+592'] },
  { code: 'HK', dialCodes: ['+852'] },
  { code: 'HN', dialCodes: ['+504'] },
  { code: 'HR', dialCodes: ['+385'] },
  { code: 'HT', dialCodes: ['+509'] },
  { code: 'HU', dialCodes: ['+36'] },
  { code: 'ID', dialCodes: ['+62'] },
  { code: 'IE', dialCodes: ['+353'] },
  { code: 'IL', dialCodes: ['+972'] },
  { code: 'IM', dialCodes: ['+44'] },
  { code: 'IN', dialCodes: ['+91'] },
  { code: 'IO', dialCodes: ['+246'] },
  { code: 'IQ', dialCodes: ['+964'] },
  { code: 'IR', dialCodes: ['+98'] },
  { code: 'IS', dialCodes: ['+354'] },
  { code: 'IT', dialCodes: ['+39'] },
  { code: 'JE', dialCodes: ['+44'] },
  { code: 'JM', dialCodes: ['+1'] },
  { code: 'JO', dialCodes: ['+962'] },
  { code: 'JP', dialCodes: ['+81'] },
  { code: 'KE', dialCodes: ['+254'] },
  { code: 'KG', dialCodes: ['+996'] },
  { code: 'KH', dialCodes: ['+855'] },
  { code: 'KI', dialCodes: ['+686'] },
  { code: 'KM', dialCodes: ['+269'] },
  { code: 'KN', dialCodes: ['+1'] },
  { code: 'KP', dialCodes: ['+850'] },
  { code: 'KR', dialCodes: ['+82'] },
  { code: 'KW', dialCodes: ['+965'] },
  { code: 'KY', dialCodes: ['+1'] },
  { code: 'KZ', dialCodes: ['+7'] },
  { code: 'LA', dialCodes: ['+856'] },
  { code: 'LB', dialCodes: ['+961'] },
  { code: 'LC', dialCodes: ['+1'] },
  { code: 'LI', dialCodes: ['+423'] },
  { code: 'LK', dialCodes: ['+94'] },
  { code: 'LR', dialCodes: ['+231'] },
  { code: 'LS', dialCodes: ['+266'] },
  { code: 'LT', dialCodes: ['+370'] },
  { code: 'LU', dialCodes: ['+352'] },
  { code: 'LV', dialCodes: ['+371'] },
  { code: 'LY', dialCodes: ['+218'] },
  { code: 'MA', dialCodes: ['+212'] },
  { code: 'MC', dialCodes: ['+377'] },
  { code: 'MD', dialCodes: ['+373'] },
  { code: 'ME', dialCodes: ['+382'] },
  { code: 'MF', dialCodes: ['+590'] },
  { code: 'MG', dialCodes: ['+261'] },
  { code: 'MH', dialCodes: ['+692'] },
  { code: 'MK', dialCodes: ['+389'] },
  { code: 'ML', dialCodes: ['+223'] },
  { code: 'MM', dialCodes: ['+95'] },
  { code: 'MN', dialCodes: ['+976'] },
  { code: 'MO', dialCodes: ['+853'] },
  { code: 'MP', dialCodes: ['+1'] },
  { code: 'MQ', dialCodes: ['+596'] },
  { code: 'MR', dialCodes: ['+222'] },
  { code: 'MS', dialCodes: ['+1'] },
  { code: 'MT', dialCodes: ['+356'] },
  { code: 'MU', dialCodes: ['+230'] },
  { code: 'MV', dialCodes: ['+960'] },
  { code: 'MW', dialCodes: ['+265'] },
  { code: 'MX', dialCodes: ['+52'] },
  { code: 'MY', dialCodes: ['+60'] },
  { code: 'MZ', dialCodes: ['+258'] },
  { code: 'NA', dialCodes: ['+264'] },
  { code: 'NC', dialCodes: ['+687'] },
  { code: 'NE', dialCodes: ['+227'] },
  { code: 'NF', dialCodes: ['+672'] },
  { code: 'NG', dialCodes: ['+234'] },
  { code: 'NI', dialCodes: ['+505'] },
  { code: 'NL', dialCodes: ['+31'] },
  { code: 'NO', dialCodes: ['+47'] },
  { code: 'NP', dialCodes: ['+977'] },
  { code: 'NR', dialCodes: ['+674'] },
  { code: 'NU', dialCodes: ['+683'] },
  { code: 'NZ', dialCodes: ['+64'] },
  { code: 'OM', dialCodes: ['+968'] },
  { code: 'PA', dialCodes: ['+507'] },
  { code: 'PE', dialCodes: ['+51'] },
  { code: 'PF', dialCodes: ['+689'] },
  { code: 'PG', dialCodes: ['+675'] },
  { code: 'PH', dialCodes: ['+63'] },
  { code: 'PK', dialCodes: ['+92'] },
  { code: 'PL', dialCodes: ['+48'] },
  { code: 'PM', dialCodes: ['+508'] },
  { code: 'PR', dialCodes: ['+1'] },
  { code: 'PS', dialCodes: ['+970'] },
  { code: 'PT', dialCodes: ['+351'] },
  { code: 'PW', dialCodes: ['+680'] },
  { code: 'PY', dialCodes: ['+595'] },
  { code: 'QA', dialCodes: ['+974'] },
  { code: 'RE', dialCodes: ['+262'] },
  { code: 'RO', dialCodes: ['+40'] },
  { code: 'RS', dialCodes: ['+381'] },
  { code: 'RU', dialCodes: ['+7'] },
  { code: 'RW', dialCodes: ['+250'] },
  { code: 'SA', dialCodes: ['+966'] },
  { code: 'SB', dialCodes: ['+677'] },
  { code: 'SC', dialCodes: ['+248'] },
  { code: 'SD', dialCodes: ['+249'] },
  { code: 'SE', dialCodes: ['+46'] },
  { code: 'SG', dialCodes: ['+65'] },
  { code: 'SH', dialCodes: ['+290'] },
  { code: 'SI', dialCodes: ['+386'] },
  { code: 'SJ', dialCodes: ['+47'] },
  { code: 'SK', dialCodes: ['+421'] },
  { code: 'SL', dialCodes: ['+232'] },
  { code: 'SM', dialCodes: ['+378'] },
  { code: 'SN', dialCodes: ['+221'] },
  { code: 'SO', dialCodes: ['+252'] },
  { code: 'SR', dialCodes: ['+597'] },
  { code: 'SS', dialCodes: ['+211'] },
  { code: 'ST', dialCodes: ['+239'] },
  { code: 'SV', dialCodes: ['+503'] },
  { code: 'SX', dialCodes: ['+1'] },
  { code: 'SY', dialCodes: ['+963'] },
  { code: 'SZ', dialCodes: ['+268'] },
  { code: 'TA', dialCodes: ['+290'] },
  { code: 'TC', dialCodes: ['+1'] },
  { code: 'TD', dialCodes: ['+235'] },
  { code: 'TG', dialCodes: ['+228'] },
  { code: 'TH', dialCodes: ['+66'] },
  { code: 'TJ', dialCodes: ['+992'] },
  { code: 'TK', dialCodes: ['+690'] },
  { code: 'TL', dialCodes: ['+670'] },
  { code: 'TM', dialCodes: ['+993'] },
  { code: 'TN', dialCodes: ['+216'] },
  { code: 'TO', dialCodes: ['+676'] },
  { code: 'TR', dialCodes: ['+90'] },
  { code: 'TT', dialCodes: ['+1'] },
  { code: 'TV', dialCodes: ['+688'] },
  { code: 'TW', dialCodes: ['+886'] },
  { code: 'TZ', dialCodes: ['+255'] },
  { code: 'UA', dialCodes: ['+380'] },
  { code: 'UG', dialCodes: ['+256'] },
  { code: 'US', dialCodes: ['+1'] },
  { code: 'UY', dialCodes: ['+598'] },
  { code: 'UZ', dialCodes: ['+998'] },
  { code: 'VA', dialCodes: ['+39'] },
  { code: 'VC', dialCodes: ['+1'] },
  { code: 'VE', dialCodes: ['+58'] },
  { code: 'VG', dialCodes: ['+1'] },
  { code: 'VI', dialCodes: ['+1'] },
  { code: 'VN', dialCodes: ['+84'] },
  { code: 'VU', dialCodes: ['+678'] },
  { code: 'WF', dialCodes: ['+681'] },
  { code: 'WS', dialCodes: ['+685'] },
  { code: 'XK', dialCodes: ['+383'] },
  { code: 'YE', dialCodes: ['+967'] },
  { code: 'YT', dialCodes: ['+262'] },
  { code: 'ZA', dialCodes: ['+27'] },
  { code: 'ZM', dialCodes: ['+260'] },
  { code: 'ZW', dialCodes: ['+263'] },
];

function getDisplayNames() {
  if (typeof Intl === 'undefined' || typeof Intl.DisplayNames !== 'function') {
    return null;
  }
  try {
    return new Intl.DisplayNames(['en'], { type: 'region' });
  } catch {
    return null;
  }
}

const displayNames = getDisplayNames();

function resolveCountryName(code) {
  if (REGION_NAME_OVERRIDES[code]) return REGION_NAME_OVERRIDES[code];
  return displayNames?.of(code) || code;
}

export const PHONE_COUNTRIES = RAW_PHONE_COUNTRIES
  .map((item) => {
    const name = resolveCountryName(item.code);
    return {
      ...item,
      name,
      dialCode: item.dialCodes[0] || '',
      label: `${name} (${item.dialCodes[0] || ''})`,
    };
  })
  .sort((left, right) => left.name.localeCompare(right.name));

export function getDialCodeForRegion(regionCode) {
  return PHONE_COUNTRIES.find((item) => item.code === String(regionCode || '').toUpperCase())?.dialCode || '';
}

export function getDefaultPhoneRegion() {
  if (typeof navigator !== 'undefined') {
    const locale = String(navigator.language || navigator.languages?.[0] || '').trim();
    const region = locale.includes('-') ? locale.split('-').pop() : '';
    const normalized = String(region || '').toUpperCase();
    if (normalized && PHONE_COUNTRIES.some((item) => item.code === normalized)) {
      return normalized;
    }
  }
  return 'US';
}

export function buildInternationalPhoneNumber(regionCode, localNumber) {
  const rawNumber = String(localNumber || '').trim();
  if (!rawNumber) return '';
  if (rawNumber.startsWith('+')) return rawNumber;

  const dialCode = getDialCodeForRegion(regionCode);
  const digitsOnly = rawNumber.replace(/[^\d]/g, '');
  if (!digitsOnly) return '';
  if (!dialCode) return digitsOnly;
  return `${dialCode}${digitsOnly.replace(/^0+/, '')}`;
}
